### ISSUE TITLE
not able to clone the repo using wget -O - https://wire.my.to/setup-wire-pod.sh | bash

### ISSUE THREAD

**Issue by kakashi2018** [kercre123/wire-prod-pod#1]
stuck at this 
wget -O - https://wire.my.to/setup-wire-pod.sh | bash
--2022-08-28 08:36:39--  https://wire.my.to/setup-wire-pod.sh
Resolving wire.my.to (wire.my.to)... 173.20.162.183
Connecting to wire.my.to (wire.my.to)|173.20.162.183|:443...

**Comment by kercre123** [comment]
Try it now, my server was down for a little while.
