### ISSUE TITLE
wire-prod-pod unstable after reinstallation

### ISSUE THREAD

**Issue by Skybird129** [kercre123/wire-prod-pod#10]
Hi,
I'm running wire-prod-pod on a Raspberry Pi 4B 8GB. This morning I didn't see the changes concerning VOSK and OpenWeatherMap, so I decided to run the update script manually:
`cd ~/wire-prod-pod/`
`sudo ./update.sh`

However, I got an error message stating that `~/wire-prod-pod/chipper/go.mod` and `~/wire-prod-pod/chipper/go.sum` already exist and can't be overwritten. I deleted these two files and ran the update script again.

Now I got an error message stating that VOSK is missing. I decided to uninstall and reinstall wire-prod-pod:
`sudo ./uninstall.sh`
`sudo reboot`
`cd ~`
`sudo rm -r ./wire-prod-pod/`
`sudo reboot`
`cd ~`
`wget -O - https://keriganc.com/setup-wire-pod.sh | bash`
`sudo reboot`

I configured wire-prod-pod using the web interface: 
- Speech-to-text service: VOSK
- Hostname: escapepod.local
- Weather: Yes (I inserted my API key)
- Knowledge Graph: Yes (I pasted my Client ID and Client Key)

I rebooted just to make sure and configured our two Vectors. 

After another reboot, everything worked at the beginning. After a few questions, the log in the web interface on my laptop didn't refresh. Reloading the page lead to the error: "The connection was reset." I connected via VNC to escapepod.local and opened the web interface. See wire-pod logs was just an empty white page. 

After rebooting the Pi, wire-prod-pod works again for a short time. I also tried switching back to Coqui without success. Without the reboots, wire-prod-pod hangs during configuration.

Any help would be appreciated. Thanks.

**Comment by kercre123** [comment]
May you paste the output of `systemctl status wire-pod` and try running `systemctl restart wire-pod`?

I have also come across the go.mod and go.sum issues, those appear to get edited by Go whenever the program is built. I may have to slightly overhaul the update system.

**Comment by Skybird129** [comment]
Sure. Here it the output of `sudo systemctl status wire-pod`:
● wire-pod.service - Wire Escape Pod (coqui)
     Loaded: loaded (/lib/systemd/system/wire-pod.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2022-11-07 07:56:51 UTC; 2min 4s ago
    Process: 1987 ExecStart=/home/ep-admin/wire-prod-pod/chipper/start.sh (code=exited, status=2)
   Main PID: 1987 (code=exited, status=2)
        CPU: 22.598s

Nov 07 07:56:51 escapepod start.sh[1988]:         /root/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:1564 +0xdd8
Nov 07 07:56:51 escapepod start.sh[1988]: google.golang.org/grpc.(*Server).handleStream(0x40001ea000, {0x29b3e50, 0x4001f511e>
Nov 07 07:56:51 escapepod start.sh[1988]:         /root/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:1646 +0x828
Nov 07 07:56:51 escapepod start.sh[1988]: google.golang.org/grpc.(*Server).serveStreams.func1.2()
Nov 07 07:56:51 escapepod start.sh[1988]:         /root/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:938 +0x88
Nov 07 07:56:51 escapepod start.sh[1988]: created by google.golang.org/grpc.(*Server).serveStreams.func1
Nov 07 07:56:51 escapepod start.sh[1988]:         /root/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:936 +0x29c
Nov 07 07:56:51 escapepod systemd[1]: wire-pod.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 07 07:56:51 escapepod systemd[1]: wire-pod.service: Failed with result 'exit-code'.
Nov 07 07:56:51 escapepod systemd[1]: wire-pod.service: Consumed 22.598s CPU time.
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
lines 1-17/17 (END)

**Comment by Skybird129** [comment]
Sorry, forgot to mention: The Pi is running the 64 bits version of Raspberry Pi OS with desktop with all updates installed.

**Comment by kercre123** [comment]
I think I may have fixed the issue in an earlier commit, are you still experiencing it?

**Comment by Skybird129** [comment]
Sorry for my late reply.

Yes, I'm still experiencing the issue. When I tried to test it today (hadn't used voice commands since), wire-prod-pod wasn't working. I restarted the Pi and asked our two Vectors for the weather in New York, San Francisco and Orlando. When I wanted to ask them a fourth time, wire-prod-pod hung again.

**Comment by Skybird129** [comment]
Yesterday, I also tried a complete reinstall of the Raspberry Pi, but it didn't solve the problem.

**Comment by Skybird129** [comment]
After the last update, I reinstalled wire-prod-pod again (see also #14) and it has fixed this problem. Thanks a lot.
