### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by raymck** [kercre123/wire-prod-pod#11]
Instead of starting a PR, I thought I'd check first to see how you view this should be handled -- documentation, shell script, or is not an issue.

With a fresh standard debian install, installing the following packages is required before the setup script (and postinstallation) completes successfully: git, avahi-daemon, and unzip. This is, of course, a trivial matter for someone with linux experience, but it seems like you're aiming for a "one-click install" with the wire-prod-pod project.

**Comment by kercre123** [comment]
Just added those packages to the setup.sh - a PR is most appreciated but I don't really mind how an issue is brought up
