### ISSUE TITLE
Trouble Updating wire-prod-pod - Reinstalling Seems to Help

### ISSUE THREAD

**Issue by Skybird129** [kercre123/wire-prod-pod#14]
Yesterday, I did a complete reinstall of the Raspberry Pi running wire-prod-pod. Today (after the auto-update) I discovered a new enhancement to wire-prod-pod "Configure bot settings (similar to Vector mobile app)." However, when I tried to click that hyperlink, I got a 404 error. 

I tried restarting the Raspberry Pi and still got the error. So I thought a manual update might fix it. After stopping the wire-pod service I ran sudo ./update.sh. Unfortunately, I lost the original output, but I got an error message about a missing or not found package and should add it to the PKG_CONFIG_PATH environment variable.

After update.sh completed, the new link was gone. I decided to uninstall and reinstall wire-prod-pod and now the link seems to work. I didn't check it further as I don't want to clear Vector's User data.

**Comment by EchoInCloud** [comment]
https://github.com/kercre123/wire-pod/issues/40#top

**Comment by kercre123** [comment]
Added libasound2-dev to postupdate.sh which should fix the issue, originally I only had it in setup.sh.
