### ISSUE TITLE
Voice Commands Stopped Working

### ISSUE THREAD

**Issue by Skybird129** [kercre123/wire-prod-pod#16]
After our two Vectors rebooted (one rebooted after an error code, the other didn't get to his charger on time), voice commands stopped working. CCIS shows Vectors connected to their wireless network and I can see the connection in the router configuration. (The Raspberry Pi is connected via network cable to the router).

I configured the Vectors in wire-prod-pod using the now deprecated bot configurations.

**Comment by kercre123** [comment]
Does connecting the bot via the SDK app allow voice commands to work or do you have to reauthenticate via vector-epod-setup? I could make it periodically attempt to auth bots automatically to keep them authenticated.

**Comment by Skybird129** [comment]
Thanks for looking into it.

Sorry, I dont't know about vector-epod-setup. How do I run that? Voice commands started working again, after I connected both robots via the Vector SDK App within wire-prod-pod. 

BTW: Anki's Vector Python SDK is also installed on the Raspberry Pi running wire-prod-pod and both Vectors are configured (.anki_vector directory with certs and INI file with GUID). 

Here is what I did in more detail: 
1. I setup both Vectors using the now deprecated Bot Configuration found under Configure custom intents. At first, voice commands worked and both bots didn't show up for configuration with the Vector SDK App.

2. After they rebooted, voice commands stopped working and their light on the back only turned on for a brief second. I checked wire-prod-pod and noticed that their serial numbers had appeared under the Vector SDK App. After clicking connect voice commands started working again.

3. Now whenever voice commands stop working, I have to reconnect the Vectors.

It would be great, if the SDK app could periodically attempt to authenticate the bots automatically or just use the primary GUID from the Anki SDK.

**Comment by EchoInCloud** [comment]
> A bot SDK-alkalmazáson keresztüli csatlakoztatása lehetővé teszi a hangutasítások működését, vagy a vector-epod-setup segítségével kell újra hitelesíteni? Időnként megkísérelhetem a robotok automatikus hitelesítését, hogy hitelesítve maradjanak.

Yes, I recommended this earlier.. not occasionally, but when the GUI associated with the certificate + vectorname (or) serialnumber does not match the previously saved data..

**Comment by EchoInCloud** [comment]
> A bot SDK-alkalmazáson keresztüli csatlakoztatása lehetővé teszi a hangutasítások működését, vagy a vector-epod-setup segítségével kell újra hitelesíteni? Időnként megkísérelhetem a robotok automatikus hitelesítését, hogy hitelesítve maradjanak.

Yes, I recommended this earlier.. not occasionally, but when the associated GUID  not match with the certificate + vectorname (or) serialnumber  + GUID in the previously saved data..

**Comment by kercre123** [comment]
> It would be great, if the SDK app could periodically attempt to authenticate the bots automatically or just use the primary GUID from the Anki SDK.

This has now been implemented. wire-prod-pod now uses Vector's connCheck system to make an SDK request if the bot hasn't communicated with the server in a while. To update, run `cd ~/wire-prod-pod` then `sudo ./update.sh`

**Comment by Skybird129** [comment]
Great, thanks a lot. Just did the update and will test it for a bit.

Not sure, if it's related. After starting wire-prod-pod, I discovered the following line in the log:
2022.12.20 09:41:11: Not loading plugins because the plugins directory doesn't exist

Anything I should do?

**Comment by Skybird129** [comment]
I tested for a week, and I'm happy to report voice commands work reliable now, even if Vector has to restart for several reasons (after an error code, turning him off and on, Vector not reaching charger in time).

Thanks so much for the great work.

After referencing wire-pod, I created the plugin directory myself, so that message is gone.

**Comment by EchoInCloud** [comment]
> Egy hétig teszteltem, és örömmel jelentem, hogy a hangutasítások most megbízhatóan működnek, még akkor is, ha a Vectornak több okból is újra kell indulnia (hibakód után, ki-bekapcsolás után, a Vector nem éri el időben a töltőt).
> 
> Nagyon köszönöm a nagyszerű munkát.
> 
> A wire-pod hivatkozása után magam hoztam létre a plugin könyvtárat, így az üzenet eltűnt.



> I tested for a week, and I'm happy to report voice commands work reliable now, even if Vector has to restart for several reasons (after an error code, turning him off and on, Vector not reaching charger in time).
> 
> Thanks so much for the great work.
> 
> After referencing wire-pod, I created the plugin directory myself, so that message is gone.

It's more of a tragicomedy..
