### ISSUE TITLE
Question regarding ads queries

### ISSUE THREAD

**Issue by raymck** [kercre123/wire-prod-pod#18]
My wire-prod-pod VM is making a lot of DNS queries to mobile app tracking sites, advertising sites, googlevideo.com, youtube, tiktok ads, etc, etc. All of these aren't getting past my DNS hole, but I'm curious what is doing it and wanted to raise awareness.

Is this one of the binary blobs doing this? I'm not great at grep, but I've not found anything else that would be causing this.
I'm running only wire-prod-pod in a bare-bones debian VM.

**Comment by raymck** [comment]
I see now the update with the SDK app. I'm pseudo-randomly guessing that the original app was lifted mostly whole, along with all the cruft.

**Comment by kercre123** [comment]
I have not seen wire-prod-pod make any requests to any URLs other than the ones for the weather API and Houndify. Are you absolutely sure it is coming from wire-prod-pod? The only proprietary blobs involved with wire-prod-pod are the Picovoice libraries, and even then I have looked through the blob and couldn't find any of the URLs mentioned.

**Comment by raymck** [comment]
Here's a snippet from Pi-hole when I asked Vector about the weather.
![escapepod-pihole](https://user-images.githubusercontent.com/588731/208153380-a1a06eec-108c-4487-8892-8411c199a2f9.png)
Do you have a suggestion on how I could discover which processes are making these calls?
