### ISSUE TITLE
Wire prod pod Installation and epod setup pages are down  

### ISSUE THREAD

**Issue by KockBurn** [kercre123/wire-prod-pod#20]
I attempted a fresh install of wire-prod-pod on a new Pi4b today. 

Both the epod setup for vector and wire prod pod pages are down. Connection timed out and domain can’t be reached errors.

**Comment by kercre123** [comment]
The vector-epod-setup page should be up now, it is running on my personal server and the winter hasn't been nice to my internet access. It will be transferred to a more stable server instance once I have the page more finalized.

**Comment by KockBurn** [comment]
Thanks, worked without issues
