### ISSUE TITLE
Error logging in. The bot is likely unable to communicate with your wire-pod instance.

### ISSUE THREAD

**Issue by CaptainBulba** [kercre123/wire-prod-pod#24]
Hello, 

I am trying to finish up Vector set up, but I cannot proceed with the last steps

I am getting Error logging in. The bot is likely unable to communicate with your wire-pod instance. Make sure you followed all of the steps and try again when I press 'Activate' 

Wire pod seems to be functional: 

[Back](http://192.168.1.28:8080/)
2022.12.31 19:06:59: Loading intent 28 --> intent_imperative_apologize( 6 keyphrases )
2022.12.31 19:06:59: Loading intent 29 --> intent_imperative_backup( 1 keyphrases )
2022.12.31 19:06:59: Loading intent 30 --> intent_imperative_volumedown( 5 keyphrases )
2022.12.31 19:06:59: Loading intent 31 --> intent_imperative_volumeup( 5 keyphrases )
2022.12.31 19:06:59: Loading intent 32 --> intent_imperative_lookatme( 2 keyphrases )
2022.12.31 19:06:59: Loading intent 33 --> intent_imperative_volumelevel_extend( 3 keyphrases )
2022.12.31 19:06:59: Loading intent 34 --> intent_imperative_shutup( 1 keyphrases )
2022.12.31 19:06:59: Loading intent 35 --> intent_greeting_hello( 9 keyphrases )
2022.12.31 19:06:59: Loading intent 36 --> intent_imperative_come( 2 keyphrases )
2022.12.31 19:06:59: Loading intent 37 --> intent_imperative_love( 2 keyphrases )
2022.12.31 19:06:59: Loading intent 38 --> intent_knowledge_promptquestion( 2 keyphrases )
2022.12.31 19:06:59: Loading intent 39 --> intent_clock_checktimer( 9 keyphrases )
2022.12.31 19:06:59: Loading intent 40 --> intent_global_stop_extend( 8 keyphrases )
2022.12.31 19:06:59: Loading intent 41 --> intent_clock_settimer_extend( 5 keyphrases )
2022.12.31 19:06:59: Loading intent 42 --> intent_clock_time( 4 keyphrases )
2022.12.31 19:06:59: Loading intent 43 --> intent_imperative_quiet( 2 keyphrases )
2022.12.31 19:06:59: Loading intent 44 --> intent_imperative_dance( 3 keyphrases )
2022.12.31 19:06:59: Loading intent 45 --> intent_play_pickupcube( 6 keyphrases )
2022.12.31 19:06:59: Loading intent 46 --> intent_imperative_fetchcube( 3 keyphrases )
2022.12.31 19:06:59: Loading intent 47 --> intent_imperative_findcube( 2 keyphrases )
2022.12.31 19:06:59: Loading intent 48 --> intent_play_anytrick( 3 keyphrases )
2022.12.31 19:06:59: Loading intent 49 --> intent_message_recordmessage_extend( 1 keyphrases )
2022.12.31 19:06:59: Loading intent 50 --> intent_message_playmessage_extend( 4 keyphrases )
2022.12.31 19:06:59: Loading intent 51 --> intent_blackjack_hit( 1 keyphrases )
2022.12.31 19:06:59: Loading intent 52 --> intent_blackjack_stand( 2 keyphrases )
2022.12.31 19:06:59: Loading intent 53 --> intent_play_keepaway( 2 keyphrases )
2022.12.31 19:06:59: Loading plugins
2022.12.31 19:06:59: Houndify for knowledge graph initialized!
2022.12.31 19:06:59: Serving cmux

**Comment by kercre123** [comment]
May you provide more info about your setup, such as what device wire-pod is running on and its operating system? Is this device and your Vector on the same network?

**Comment by CaptainBulba** [comment]
I am trying to run wire pod on Orange Pi 3 LTS - Armbian 22.11.1 Jammy

and I am trying to log in Vector with Windows 10. 

Vector, Orange Pi and Windows 10 laptop are on the same network (orange Pi connected via ethernet, Windows 10 / Vector Wifi). 

I also tried uninstalling wire prod pod and trying to go with just wire prod (following all steps), still have exactly the same error.

**Comment by kercre123** [comment]
On the Orange Pi, may you run `sudo systemctl status avahi-daemon` and send the output here?
