### ISSUE TITLE
Houndify Stopped Working

### ISSUE THREAD

**Issue by Skybird129** [kercre123/wire-prod-pod#26]
Hi.

When I try to use the knowledge graph, Vector reacts to "Hey Vector. - I have a question" with "Ready". After I ask something, Vector drops the tiny squares on his screen and makes the no sound. This happens to both our Vectors for about a week. (It used to work before.) They can connect to wire-prod-pod and wire-prod-pod can access the internet. Houndify is up and doesn't show any used credits. Entering client id and client key in wire-prod-pod again as well as restating and manually updating wire-prod-pod didn't help.

I'm running wire-prod-pod on a Raspberry Pi 4B 8 GB with Raspberry Pi OS (64-bit) with Desktop.

**Comment by kercre123** [comment]
Just pushed a fix, try updating now. This was an issue in wire-pod which got fixed in a PR, but I forgot to also fix it in wire-prod-pod.

**Comment by Skybird129** [comment]
Just updated and it's working now. Thanks a lot.
