### ISSUE TITLE
Cannot start wire-pod on Ubuntu

### ISSUE THREAD

**Issue by MTrab** [kercre123/wire-prod-pod#5]
I just get this, when I try starting wire-pod on my Ubuntu:

```
● wire-pod.service - Wire Escape Pod (coqui)
   Loaded: loaded (/lib/systemd/system/wire-pod.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2022-10-07 22:03:09 CEST; 4 days ago
  Process: 37577 ExecStart=/home/malene/wire-pod/chipper/start.sh (code=exited, status=1/FAILURE)
 Main PID: 37577 (code=exited, status=1/FAILURE)

okt 07 22:03:09 escapepod systemd[1]: Started Wire Escape Pod (coqui).
okt 07 22:03:09 escapepod start.sh[37577]: go: module cache not found: neither GOMODCACHE nor GOPATH is set
okt 07 22:03:09 escapepod systemd[1]: wire-pod.service: Main process exited, code=exited, status=1/FAILURE
okt 07 22:03:09 escapepod systemd[1]: wire-pod.service: Failed with result 'exit-code'.
```

Any ideas?

**Comment by MTrab** [comment]
Removed everything and started over - now that part works :D

**Comment by MTrab** [comment]
Aaaaaand - just reinstalled on a RPi, and getting this again. A reinstall doesn't seem to work this time around :(

**Comment by Lodenk** [comment]
I am having the same issue:
Oct 13 17:31:11 escapepod start.sh[3801]: go: module cache not found: neither GOMODCACHE nor GOPATH is set
Oct 13 17:31:11 escapepod start.sh[3801]: go: module cache not found: neither GOMODCACHE nor GOPATH is set
Oct 13 17:31:11 escapepod start.sh[3801]: go: module cache not found: neither GOMODCACHE nor GOPATH is set

RPI fresh raspian

**Comment by kercre123** [comment]
It looks like you are using [wire-pod](https://github.com/kercre123/wire-pod) rather than wire-prod-pod, is that correct? May you send the output of `ls ~/wire-pod/chipper`? This error should not happen if the `chipper` binary exists in that folder.

**Comment by MTrab** [comment]
Tried both.
Same error weather I use wire-pod or wire-prod-pod.

**Comment by MTrab** [comment]
Okay - found the solution. You need to login as root and start the service that way.
Sudu starting the service isn't enough
