### ISSUE TITLE
https://keriganc.com/vector-epod-setup user login is not working

### ISSUE THREAD

**Issue by MTrab** [kercre123/wire-prod-pod#6]
When trying to use https://keriganc.com/vector-epod-setup  to downgrade, I get to the point where I need to authorize vector with the account from the app.
But I keep getting error logging in and cannot get any further - what to do?

**Comment by kercre123** [comment]
That site should only be used to apply the OTA update. Once that has completed, close the tab and do not attempt to authenticate.

**Comment by MTrab** [comment]
It never did complete. Found another guide pointing me to project-victor and via some commands got it flashed that way.

Now I only need to find some kind of log where I can see if the Vector actually communicates with wire-pod
